ytdl.py

去BotFather那为你的bot加一个`ytdl`命令，把bot添加到群组，就能通过`/ytdl`调用。

add group usage

---

ytdl.py

p站的视频格式有一定的欺骗性，默认只能抓到720的，这样改一下就能抓1080了。
测试链接：
https://www.pornhub.com/view_video.php?viewkey=ph5fcb8bad75124

fix pornhub

---

ytdlbot/config.py

Previously "False" counted as True because string to boolean conversion

Now VIP can be disabled

---

ytdlbot/tasks.py

Fix error cache

---

README.md
ytdlbot/config.py
ytdlbot/ytdl_bot.py

Some dirty way to implement Env file config for playlist download

Env toggle to enable / disable Playlist download

---

ytdlbot/constant.py
ytdlbot/utils.py

No one uses res. 360p these days and it's important to have a option to choose 720p. So please change these.

Changed video quality choices

---

ytdlbot/constant.py
ytdlbot/limit.py
ytdlbot/ytdl_bot.py

Ref: https://github.com/tgbot-collection/ytdlbot/commit/c51032373f25bdbbe0dd782b443f3e2381bb9728

Revert commit

---

README.md
ytdlbot/config.py
ytdlbot/ytdl_bot.py

Env toggle to enable / disable m3u8 download

---

.github/workflows/builder.yaml
requirements.txt
ytdlbot/config.py

Merging these changes from Master into pyrogram-v2:
1. [drop armv7](https://github.com/tgbot-collection/ytdlbot/commit/aae0f9270cc82317d83b02975cdc0020bca53b4d)
2. [double default limits](https://github.com/tgbot-collection/ytdlbot/commit/73bdf2a54d3c8a1242d9d0121418a316e51b194c)

Syncing 'pyrogram-v2' branch with 'master' branch

---

README.md

Improve "Run natively on your machine" guide to step by step guide with commands for beginners.

Update README.md (Improve)

---

ytdlbot/database.py

check if the connection exists, and reconnect if disconnected.

Update database.py - pymysql.err.InterfaceError: (0,”) error

---

ytdlbot/tasks.py

Clean resond from yt-dlp download errror

---

README.md
ytdlbot/sp_downloader.py

Benny, Feel free to make any corrections you see fit. Thanks.

Add support for krakenfiles.com links and improve selection process

---

requirements.txt

yt-dlp version 2024.7.2
Released: Jul 3, 2024

Bump yt-dlp from 2024.5.27 to 2024.7.2

---

README.md
ytdlbot/tasks.py
ytdlbot/utils.py
ytdlbot/ytdl_bot.py

use `/leech {url}` trigger the aria2 engine for downloading.
Starting [yt-dlp 2024.07.01](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.07.01) block downloads with unsafe extensions by default.
**Now you can use this option to download other files(including media) faster and more reliable.**

leech option for direct download using aria2

---

ytdlbot/utils.py
ytdlbot/ytdl_bot.py

New beautiful stats command,
**Owner**
**Users**

Improved `/stats` command

---

requirements.txt

Tested ✅
facebook: [Fix formats extraction](https://github.com/yt-dlp/yt-dlp/commit/ec9b25043f399de6a591d8370d32bf0e66c117f2) (https://github.com/yt-dlp/yt-dlp/issues/11343) by [kclauhk](https://github.com/kclauhk)  for #451

Bump yt-dlp from 2024.10.22 to 2024.11.04  #451

---

.github/workflows/codeql-analysis.yml
requirements.txt

Bump yt-dlp to 2024.12.23

---

.github/workflows/codeql-analysis.yml
requirements.txt

Bump yt-dlp to 2025.1.12

---

.env.example
README.md
src/config/constant.py

Improve README.md

---

src/config/config.py
src/engine/generic.py

Fix #483 & `get_env`

---

README.md
src/engine/direct.py
src/main.py

Now aria2 engine support progress bar 🙌

Improve `/direct` (aria2) command

---

src/engine/__init__.py
src/engine/direct.py
src/engine/instagram.py
src/engine/krakenfiles.py
src/engine/pixeldrain.py
src/main.py

Fixed and improved `/spdl` command and its functions.
- Instagram ✅
- pixeldrain ✅
- KrakenFiles ❌

Fix `/spdl` (refactor #460)

---

.env.example
src/config/config.py
src/main.py

m3u8 support and toggle

---

pdm.lock
pyproject.toml
requirements.txt

Bump kurigram from 2.1.38 to 2.2.0 (PDM)

---

pdm.lock
pyproject.toml
requirements.txt

kurigram 2.2.0 -> 2..2.1
yt-dlp 2025.3.31 -> 2025.4.30

Bump dependencies kurigram, yt-dlp

---

pdm.lock
pyproject.toml
requirements.txt

Bump kurigram, redis and yt-dlp to the latest version

---

pdm.lock
pyproject.toml
src/engine/__init__.py
src/engine/base.py
src/engine/instagram.py
src/main.py

- Better error handling
- Update instagram.py
- Fixed upload fail when there is only single media.
- Improve upload functions
*    Now works better with different file types.

Improve media upload reliability and error handling

---

pdm.lock
pyproject.toml
requirements.txt

Bump kurigram from 2.2.6 to 2.2.7

---

pdm.lock
pyproject.toml
requirements.txt

Bump yt-dlp[curl-cffi,default] from 2025.8.11 to 2025.8.20

---

pdm.lock
pyproject.toml
requirements.txt

Bump yt-dlp[curl-cffi,default] from 2025.8.20 to 2025.8.22

---

pdm.lock
pyproject.toml
requirements.txt

Bump kurigram and yt-dlp to the latest versions
